version: '3.7'

services:
  database:
    build:
      context: './docker/services/postgresql'
    container_name: 'sveltekit-starter-database'
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
