name: CI
on: 
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        run: npm install
      
      #- name: Run Prettier
        #run: npm run format
        
      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,ts,svelte,md}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
          
      - name: Run End to End tests
        run: npx playwright install && npm run test
        
      - name: Run Unit tests
        run: npm run test:unit
