name: CI
on: 
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          cache: npm

      - name: Install packages
        run: npm install
      
      - name: Run Prettier
        run: npm format
        
      - name: Run End to End tests
        run: npm test
        
      - name: Run Unit tests
        run: npm test:unit
