name: CI
on: 
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        run: npm install
      
      - name: Run Prettier
        run: npm run format
        
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Apply formatting changes (prettier)
          
      - name: Run End to End tests
        run: npx playwright install && npm run test
        
      - name: Run Unit tests
        run: npm run test:unit
