name: CI
on: 
  pull_request:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc' # (1)
          cache: 'npm'

      # https://dev.to/drakulavich/aggressive-dependency-caching-in-github-actions-3c64
      - name: Cache NPM dependencies # (2)
        uses: actions/cache@v3
        id: cache-primes
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies # (3)
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: npm ci
        
      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,ts,svelte,md}
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
          
      - name: Run End to End tests
        run: npx playwright install && npm run test
        
      - name: Run Unit tests
        run: npm run test:unit
